cloudfoundry/credhub

docs/credential-types.md
Prior to this fix, some examples displayed as bad YAML
=> Fix markdown rendering by github

src/main/java/org/cloudfoundry/credhub/audit/CEFAuditRecord.java, src/main/java/org/cloudfoundry/credhub/audit/EventAuditLogService.java, src/main/java/org/cloudfoundry/credhub/audit/OperationDeviceAction.java, src/main/java/org/cloudfoundry/credhub/audit/Utils.java, src/main/java/org/cloudfoundry/credhub/audit/entity/GetCredential.java, src/main/java/org/cloudfoundry/credhub/audit/entity/GetCredentialById.java, src/main/java/org/cloudfoundry/credhub/audit/entity/RequestDetails.java, src/main/java/org/cloudfoundry/credhub/config/WebMvcConfiguration.java, src/main/java/org/cloudfoundry/credhub/controller/v1/CredentialsController.java, src/main/java/org/cloudfoundry/credhub/data/CredentialDataService.java, src/main/java/org/cloudfoundry/credhub/data/CredentialVersionDataService.java, src/main/java/org/cloudfoundry/credhub/domain/SecurityEventAuditRecord.java, src/main/java/org/cloudfoundry/credhub/handler/CredentialsHandler.java, src/main/java/org/cloudfoundry/credhub/interceptor/AuditInterceptor.java, src/main/java/org/cloudfoundry/credhub/interceptor/UserContextInterceptor.java, src/main/java/org/cloudfoundry/credhub/service/AuditEventLogService.java, src/main/java/org/cloudfoundry/credhub/service/PermissionedCredentialService.java, src/main/resources/log4j2.properties, src/test/java/org/cloudfoundry/credhub/audit/CEFAuditRecordTest.java, src/test/java/org/cloudfoundry/credhub/controller/v1/CredentialsControllerGetTest.java, src/test/java/org/cloudfoundry/credhub/data/CredentialDataServiceTest.java, src/test/java/org/cloudfoundry/credhub/interceptor/AuditInterceptorTest.java
Merging the audit refactor branch with master
=> Audit refactor

src/main/java/org/cloudfoundry/credhub/audit/CEFAuditRecord.java, src/main/java/org/cloudfoundry/credhub/service/PermissionedCredentialService.java, src/test/java/org/cloudfoundry/credhub/audit/CEFAuditRecordTest.java, src/test/java/org/cloudfoundry/credhub/interceptor/AuditInterceptorTest.java, src/test/java/org/cloudfoundry/credhub/service/PermissionedCredentialServiceTest.java
[#156127217] CredHub writes "get" API requests to credhub_security_events.log
Signed-off-by: Morolayo Lambo <mlambo@pivotal.io>
=> Refactored the tests

README.md, docs/README.md, docs/authorization-and-permissions.md
[Story](https://www.pivotaltracker.com/story/show/174322077)
=> Improve permission docs

docs/authorization-and-permissions.md
[174322077](https://www.pivotaltracker.com/story/show/174322077)
=> Define abbreviations at their first use

components/auth/src/main/kotlin/org/cloudfoundry/credhub/config/OAuthProperties.kt
remove platform dependent path operation but simply concat pathes
=> Simple fix issue 266

README.md, applications/credhub-api/build.gradle
Made this work locally today and thought that it would be useful to have in repo
=> Add an option to start credhub jvm with debug agent loaded

backends/credhub/src/test/java/org/cloudfoundry/credhub/handlers/DefaultCertificatesHandlerIntegrationTest.java
=> Postgres test issues

backends/credhub/src/test/java/org/cloudfoundry/credhub/handlers/DefaultCertificatesHandlerIntegrationTest.java
- The test uses a postgresql function that does not work in postgresql 10 unless an extensions is installed in the test database
- Run the test only if the postgresql version is greater than 10
Co-authored-by: Peter Chen <peterch@vmware.com>
=> fix: a test that fails with postgresql version 10

build.gradle
* Taking a smaller step than the major bump in https://github.com/cloudfoundry/credhub/pull/417.
Co-authored-by: Alex Rocha <alexr1@vmware.com>
=> bump: springRestDocsVersion

.github/dependabot.yml
Co-authored-by: Alex Rocha <alexr1@vmware.com>
=> chore: ignore major bump for org.springframework.restdocs

build.gradle
Updating to latest snakeyaml without any vulnerabilities and ensuring subproject usage is consistent.
=> fix: update snakeyaml and ensure consistent subproject usage.

build.gradle
=> Bump springboot 2.7.12 -> 2.7.13

build.gradle
=> Require Java 11 or later for all gradle tasks

.github/workflows/unit-test.yml, build.gradle, components/credentials/src/test/kotlin/org/cloudfoundry/credhub/services/CertificateDataServiceTest.kt
- From 11 to 17
[#186054022]
_Approve but do not merge. I will merge the change along with other bump change later._
=> bump: Minimum Java version required for build

docker/start_server.sh
=> fix(docker): fix docker image startup

gradle/wrapper/gradle-wrapper.properties, gradlew.bat
- As part of monthly dependency bump tasks.
- Files have been auto-generated by `./gradlew wrapper --gradle-version=8.7`.
=> bump: Gradle version to the latest

build.gradle
- Bumped the minor/patch versions to the latest compatible ones.
=> bump: Dependency versions that we override Spring Boot's

build.gradle, components/credentials/src/main/kotlin/org/cloudfoundry/credhub/utils/PrivateKeyReader.kt
Update as required for 2.+ bouncycastle libraries.
[#TPCF-6875]
[#TPCF-6876]
=> fix: adjust to new classes for bouncycastle 2.+

.github/dependabot.yml, build.gradle
- Removed the mention of an old specific grpc version in the pinning comment.
=> doc: Fix a dependency version pinning comment

build.gradle
- fixes https://nvd.nist.gov/vuln/detail/CVE-2024-38821
=> Bump spring security to 5.8.15

components/auth/src/main/java/org/cloudfoundry/credhub/config/AuthConfiguration.java
See the commit message for the change details.
=> New oauth2 jwt decoder for both test and run

build.gradle
- Manually bumped a couple of such depedencies to the latest patches.
=> bump: dependencies that we override spring-boot bom

components/auth/src/main/java/org/cloudfoundry/credhub/config/auth/OAuth2AuthenticationExceptionHandler.java, components/auth/src/test/java/org/cloudfoundry/credhub/config/auth/OAuth2AuthenticationExceptionHandlerTest.java
Make the InsufficientAuthenticationException handling properly handle the mtls_test.go acceptance test expectations.
=> Fix the InsufficientAuthenticationException handling

applications/credhub-api/src/test/java/org/cloudfoundry/credhub/config/AuthConfigurationTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/handlers/DefaultExceptionHandlerTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateMinimumDurationTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CredentialRegenerateTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/EncryptionKeyRotatorTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/GenerateModeTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsGenerateIntegrationTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsGetIntegrationTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsTypeSpecificGenerateIntegrationTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsTypeSpecificSetIntegrationTest.java, backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/v1/interpolation/InterpolationIntegrationTest.java, backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/integration/v1/certificates/CertificatesGetConcatenateCasIntegrationTest.kt, backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/integration/v1/certificates/CertificatesGetIntegrationTest.kt, backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsGetConcatenateCasIntegrationTest.kt, backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsPostIntegrationTest.kt, components/auth/src/test/kotlin/org/cloudfoundry/credhub/auth/OAuth2ExtraValidationFilterTest.kt, components/credentials/src/test/java/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataServiceTest.java, components/encryption/src/test/java/org/cloudfoundry/credhub/data/EncryptedValueDataServiceTest.java
=> Replace deprecated annotation @MockBean and @SpyBean

backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsTypeSpecificSetIntegrationTest.java
- As the existing code that mock request body object is not working after spring boot3 migration.
- Modified the requst content to actually cause the exception to be thrown in the controller.
=> Rewrote a test case.

backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CredentialAclEnforcementTest.java
- the error is:
```
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: persistent instance references an unsaved transient instance of 'org.cloudfoundry.credhub.entity.Credential' (save the transient instance before flushing)
```
which happens at all tests where `@Transactional` is in effect and the test: 1) deletes some data created in the same method or in beforeEach/beforeAll lifecycle methods 2) and then perform any operations interacting with DB.
- this error shows up after upgrading to hibernate 6.6.x+, possibly related to: https://discourse.hibernate.org/t/instance-save-transient-before/10293 https://hibernate.atlassian.net/browse/HHH-18936
- the general idea is that related entities are not properly cleaned up, leading to orphaned …
=> fix test: org.hibernate.TransientObjectException

components/auth/src/main/java/org/cloudfoundry/credhub/config/AuthConfiguration.java, components/auth/src/main/java/org/cloudfoundry/credhub/config/AuthWithoutOAuthConfiguration.java
- Replaced with non-deprecated ones.
- Also added `UrlHandlerFilter` in `AuthWithoutOAuthConfiguration`, the same as in `AuthConfiguration`.
=> fix: Deprecated Spring API calls

components/auth/src/test/kotlin/org/cloudfoundry/credhub/auth/OAuth2ExtraValidationFilterTest.kt, components/credentials/src/main/kotlin/org/cloudfoundry/credhub/domain/CertificateGenerationParameters.kt, components/credentials/src/main/kotlin/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataService.kt, components/credentials/src/test/kotlin/org/cloudfoundry/credhub/repositories/CredentialVersionDataRepositoryTest.kt
=> Replace some deprecated usages of java libs

gradle/wrapper/gradle-wrapper.properties
Auto-generated per https://docs.gradle.org/8.14.2/release-notes.html#upgrade-instructions.
=> bump: gradle to the latest version
