cloudfoundry/credhub

src/main/java/org/cloudfoundry/credhub/util/PrivateKeyReader.java
src/main/java/org/cloudfoundry/credhub/validator/CertificateMatchesPrivateKeyValidator.java
src/main/resources/messages.properties
src/test/java/org/cloudfoundry/credhub/helper/JsonTestHelper.java
src/test/java/org/cloudfoundry/credhub/integration/CertificateSetAndRegenerateTest.java
src/test/java/org/cloudfoundry/credhub/util/TestConstants.java

Hi,
we noticed that trying to create a certificate object with a private key in PKCS8 format results in a 500 response "An application error occurred. Please contact your CredHub administrator".
On the server side an exception is thrown:
```
javax.validation.ValidationException: HV000028: Unexpected exception during isValid call.
at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:451) ~[hibernate-validator-5.3.6.Final.jar:5.3.6.Final]
at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:127) ~[hibernate-validator-5.3.6.Final.jar:5.3.6.Final]
...
Caused by: java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to …
```

[solution open for discussion] Fix error on PKCS8 keys

---

src/test/java/org/cloudfoundry/credhub/helper/JsonTestHelper.java

Without those changes I got compile errors in Eclipse with Java 8.
One of those errors:
`The method assertThat(T, Matcher<? super T>) in the type MatcherAssert is not applicable for the arguments (Set<ConstraintViolation<CertificateSetRequest>>, Matcher<Iterable<? super ConstraintViolation>>)	CertificateSetRequestTest.java	/credhub/src/test/java/org/cloudfoundry/credhub/request	line 171
`

fix Java 8 compile errors

---

src/main/java/org/cloudfoundry/credhub/request/CertificateGenerationRequestParameters.java
src/test/java/org/cloudfoundry/credhub/request/CertificateGenerationRequestParametersTest.java

- previously the limit was 64, but longer names are needed to support using bosh dns names
- dns names are limited to 253 characteres
- reference: https://tools.ietf.org/html/rfc1034
cc: @GarimaSharma

Increase the limit for SAN in certificate parameters

---

src/main/java/org/cloudfoundry/credhub/credential/JsonCredentialValue.java
src/main/java/org/cloudfoundry/credhub/domain/JsonCredentialVersion.java
src/main/java/org/cloudfoundry/credhub/util/JsonObjectMapper.java
src/test/java/org/cloudfoundry/credhub/controller/v1/CredentialsControllerTypeSpecificSetTest.java
src/test/java/org/cloudfoundry/credhub/controller/v1/InterpolationControllerTest.java
src/test/java/org/cloudfoundry/credhub/domain/CredentialFactoryTest.java
src/test/java/org/cloudfoundry/credhub/domain/JsonCredentialVersionTest.java
src/test/java/org/cloudfoundry/credhub/handler/InterpolationHandlerTest.java
src/test/java/org/cloudfoundry/credhub/request/JsonSetRequestTest.java

This PR allows CredHub to support any valid JSON, not just map. Requires a change to the CLI as well to read the values once set.
One part of the fix for cloudfoundry-incubator/credhub-cli#30

Support all valid JSON

---

docker-compose.yml
docker/config/security.yml

* In security bootstrapping, actors is an array.
* uaa requires a trailing / to correctly work (credhub CLI handles it ok with the slash, but the other library I was using didn't add the slash coming back from the /info endpoint and wasn't able to successfully login)

Fixes for docker-compose setup

---

components/credentials/src/main/java/org/cloudfoundry/credhub/validators/CAValidator.java
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/credential/CertificateCredentialValue.kt
components/credentials/src/test/java/org/cloudfoundry/credhub/requests/CertificateSetRequestTest.java

Hi @bruce-ricard
based on the comments of the PR: #139 and the Issue of: #134 the new PR  just implement / change the validation of the `CA` Certificate that we didn't break anything here.
Now there will be no error thrown if you try to import a `CA` Certificate that it not "valid" (doesn't contain the `CA:true` flag)
The import will be only accepted if the `CA` is the same as the `certificate` else the same logic as before will be used.
I also clean up the code a little bit and try that the `CAValidator` will look like `CertificateSignedByCAValidator`. 
I also added `CA` and the `CERTIFICATE` fields at the `Annotations` - `CertificateCredentialValue.kt` (Not required because we didn't use the `String[] fields` anymore but its more verbose that everyone can see what kind of fields will be …

FIX accept CA Certificate without CA flag

---

applications/credhub-api/src/test/resources/application-minimum-duration.yml
backends/credhub/src/docs/asciidoc/snippets/certificates-v1.adoc
backends/credhub/src/docs/asciidoc/snippets/credentials-v1.adoc
backends/credhub/src/docs/asciidoc/snippets/introduction.adoc
backends/credhub/src/main/kotlin/org/cloudfoundry/credhub/certificates/DefaultCertificatesHandler.kt
backends/credhub/src/main/kotlin/org/cloudfoundry/credhub/credentials/DefaultCredentialsHandler.kt
backends/credhub/src/main/kotlin/org/cloudfoundry/credhub/regenerate/DefaultRegenerateHandler.kt
backends/credhub/src/test/java/org/cloudfoundry/credhub/handlers/DefaultRegenerateHandlerTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateGenerateTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateMinimumDurationTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CredentialFindTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/GenerateModeTest.java
backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/controllers/v1/certificates/CertificatesControllerTest.kt
backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/controllers/v1/credentials/CredentialsControllerGenerateTest.kt
backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/integration/v1/credentials/CredentialsPostIntegrationTest.kt
components/credentials/src/main/java/org/cloudfoundry/credhub/generators/CertificateGenerator.java
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/credential/CertificateCredentialValue.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/domain/CertificateCredentialVersion.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/domain/CertificateGenerationParameters.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/services/DefaultCredentialService.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/views/CertificateGenerationView.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/views/CertificateView.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/views/CredentialView.kt
components/credentials/src/test/java/org/cloudfoundry/credhub/domain/CertificateGenerationParametersTest.java
components/credentials/src/test/java/org/cloudfoundry/credhub/generators/CertificateGeneratorTest.java
components/credentials/src/test/java/org/cloudfoundry/credhub/views/CertificateViewTest.java
components/permissions/src/test/kotlin/org/cloudfoundry/credhub/services/DefaultCredentialServiceTest.kt

- Receive 2 new fields in the server configuration file: ca_minimum_duration and leaf_minimum_duration
- Update cert generation/regeneration logic to use the values in these fields such that the cert gets the larger duration between the requested and the new fields
- Update converge mode logic to no longer consider the duration field
- Return a duration_overridden flag in the generate/regenerate API response when the minimum duration is used
For more information, refer this issue: https://github.com/pivotal/credhub-release/issues/60
cc @pabloarodas @ystros

Add logic to generate certificates using minimum durations

---

applications/credhub-api/build.gradle

dependabot wants to bump to major version 3
- let's do this smaller bump first

manually bump springCloudContractVersion to 2.2.8

---

applications/credhub-api/src/main/resources/db/migration/h2/V35__add_unknown_auth_method_to_request_audit_record.sql
applications/credhub-api/src/main/resources/db/migration/h2/V44__create_encrypted_value_table.sql
build.gradle

- even though this is a patch, there are some "breaking changes".
Hence, adjusting sql syntax in this commit.
- use the standard alter table / alter column statement [as
documented](https://h2database.com/html/commands.html#alter_table_alter_column)
- this version of h2 does not like the comma at the end of the
last column definition in create table statement...
- h2 is test DB only, so no implications in modifying DB migration files.
[#181598244]

Bump h2 DB to 1.4.200

---

applications/credhub-api/build.gradle
build.gradle

is DB / flyway update possible now ? because in UAA it is still with fixed versions

Dependency cleanup

---

.github/workflows/unit-test.yml

Noticed that in credhub bosh release bellsoft JDK 8 is included, so use same here for unit tests

Use credhub-release packaged version

---

hooks/pre-push

- For most of us that are not using `ssh-add`, the pre-push hook routine fails
- Some of us work around the pre-push hook failure by doing `git push --no-verify`
- By having pre-push hook that actually works, developers can be encouraged to run the pre-push hooks when pushing to `main`
[#182032196]

fix: Remove a pre-push hook routine that checks for `ssh-add -l` result

---

backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateGenerateTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateGenerateWithoutAclEnforcementTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateGetTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateVersionDeleteTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CredentialGetTest.java
backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/integration/v1/certificates/CertificatesPostIntegrationTest.kt
backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/integration/v1/regneration/RegenerateEndpointConcatenateCasIntegrationTest.kt

- When Concourse CI was upgraded to v7, some of our tests start
to timeout. These tests all generate certificates. Our current
theory is that the Concourse upgrade made the test run env take
longer to gather enough initial entropy; and these failed tests
are still using "Blocking" random generation algorithm (where the
generation process is "blocked" when the system is still trying
to gather enough entropy).
- We also observed that these slow tests are all invoking
[RequestHelper.generateCertificateCredential](https://github.com/cloudfoundry/credhub/blob/76c8c92296ecb4ef38889c9c163b38e9b7968346/backends/credhub/src/test/kotlin/org/cloudfoundry/credhub/helpers/RequestHelper.kt#L205)
to generate certificates.
- Previously, to ensure that a non-blocking entropy source is used,
we configure …

fix: tests timeout when generating certs

---

components/test-support/src/test/kotlin/org/cloudfoundry/credhub/config/ParallelPostgresTestDataSourceConfiguration.kt

This fixes an issue in which Postgres would run out of available connections, causing tests to fail.
* Close tempDataSource in createTestDatabaseForWorker()
* Configure connection pool in getParallelTestDataSource() to close idle connections after 5s and scale to 0
Written by @andreasf

fix Postgres running out of connections

---

applications/credhub-api/build.gradle
backends/credhub/build.gradle
build.gradle
components/audit/build.gradle
components/auth/build.gradle
components/credentials/build.gradle
components/encryption/build.gradle
components/errors/build.gradle
components/generate/build.gradle
components/management/build.gradle
components/permissions/build.gradle
components/string-utilities/build.gradle
components/time-support/build.gradle

jUnit versions will be handled by Spring. Remove log4j dependency declarations to simplify future analysis.

Simplify dependencies

---

.github/workflows/unit-test.yml
Dockerfile
README.md
applications/credhub-api/build.gradle
applications/credhub-api/src/main/resources/db/migration/mysql/V56__change_expiry_date_in_certificate_credential.sql
kotlin.gradle

Using Java 11 now instead of Java 8, so that we can upgrade the HikariCP library.
This will be coordinated with a PR in credhub-release.
[#184142402]

Migrate to Java 11

---

gradle/wrapper/gradle-wrapper.properties

Preparing to bump to v7.x soon. First making sure the 6.x. bump works.

bump: take latest 6.x gradle wrapper

---

backends/credhub/build.gradle

```
A problem occurred configuring project ':backends:credhub'.
> Could not resolve all artifacts for configuration ':backends:credhub:classpath'.
> Could not resolve org.ysb33r.gradle:grolifant:0.10.
Required by:
project :backends:credhub > org.asciidoctor:asciidoctor-gradle-plugin:1.6.1
> Could not resolve org.ysb33r.gradle:grolifant:0.10.
> Could not get resource 'https://repo.spring.io/plugins-release/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom'.
> Could not GET 'https://repo.spring.io/plugins-release/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom'. Received status code 401 from server:
```
- Override the gradle buildscript's transitive dependency of asciidoctor with grolifant 0.16.1, which is available in maven central.
[#185464175]

fix: Gradle clean build fails while downloading dependencies as follows:

---

backends/credhub/build.gradle
build.gradle

- Declare dependency to 'org.asciidoctor.convert.gradle.plugin' instead of `asciidoctor-gradle-plugin` and overriding 'grolifant' version. 'org.asciidoctor.convert.gradle.plugin' 2.4.0 has dependencies to later versions of 'asciidoctor-gradle-jvm and 'grolifant'.
- Add gradle plugin maven repository in build repositories for the asciidoctor task.
[#185464175]

fix: Missing asciidoctor transitive dependencies in maven repositories

---

backends/credhub/build.gradle
backends/remote/build.gradle
components/credentials/build.gradle
components/encryption/build.gradle

Reverts cloudfoundry/credhub#546 due to repeated test failures here: https://runway-ci.eng.vmware.com/teams/tas-journey-auth/pipelines/credhub-edge/jobs/test-kms-plugin-integration-jammy/builds/600.5

Revert "Build(deps): bump grpcVersion from 1.56.1 to 1.57.0"

---

backends/credhub/build.gradle
backends/remote/build.gradle
components/credentials/build.gradle
components/encryption/build.gradle

Reverts cloudfoundry/credhub#550 because it breaks a CI job related to testing KMS. Story: https://www.pivotaltracker.com/story/show/185733631

Revert "Non-Trivial - Test Failures in CI - Build(deps): bump grpcVersion from 1.56.1 to 1.57.0"

---

components/encryption/src/main/java/org/cloudfoundry/credhub/services/EncryptionKeyRotator.java

- As the rotated count can be greater than the starting count.
- Removed the log message.
[#185977500]

fix: Incorrect not-rotated record count log message

---

.github/workflows/unit-test-java11.yml

- So as to use Java11 in the branch, while keep using Java8 in other branches
[#184142402]

Add separate GitHub workflow config for unit-testing java11 branch

---

README.md

* On https://www.oracle.com/java/technologies/javase-jce-all-downloads.html it says "JDK 9 and later offer the stronger cryptographic algorithms by default."
* CredHub now requires Java 11+.
* Have not tested CredHub with the Oracle JRE.
[#184142402]

doc: remove section on crippled cryptographic capability in Oracle JDK

---

docs/credhub-security-faq.md

- Updated a Java version reference.
- Also, not related to Java 11 bump, removed duplicate mentions of JCA & JCE from the crypto lib list.
- Confirmed that other contents in the faq was still proper.
[#184142402]

docs: Update for Java 11

---

Dockerfile

- Bump JDK & JRE to 17.
- Switch the base image to BellSoft one as there is no separate jre image for openjdk 17.
- Also, we package credhub with BellSoft JRE so using BellSoft Java image makes sense.
[#186054022]
_Approve but do not merge. I will merge the change along with other bump changes later._

bump: The Java version in credhub Dockerfile

---

gradle/wrapper/gradle-wrapper.properties
gradlew

bump: Gradle to the latest

---

applications/credhub-api/build.gradle
backends/remote/build.gradle
components/auth/build.gradle
components/encryption/build.gradle
components/management/build.gradle
components/test-support/build.gradle

- bcprov-jdk15on is a transitive dep we get from using spring-security-oauth2-autoconfigure, which is an EOL lib (and hence does not have further patches) we will replace.
- The bcprov-jdk15on version here is flagged with CVE-2020-0187 and CVE-2023-33201.
- Exclude bcprov-jdk15on to address these CVEs.
- gradle doc on the exclude statement: https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps

fix: exclude unused vulnerable transitive dep bcprov-jdk15on

---

build.gradle

Reverts cloudfoundry/credhub#634

Revert "Build(deps): bump springBootVersion from 2.7.17 to 2.7.18"

---

backends/remote/build.gradle
components/encryption/build.gradle

* Had a build error related to grpc-netty trying to pin netty to 4.1.102 or 4.1.104:
```
> Could not find netty-transport-native-epoll-4.1.101.Final-linux-riscv64.jar (io.netty:netty-transport-native-epoll:4.1.101.Final).
```
* Could not find a reason to pin the netty version. We're hoping the original reason is no longer valid.
[#186764106]

fix build error with netty bump

---

docs/credhub-security-faq.md

* "generates" isn't the correct word here. CredHub doesn't generate a key. It calculates (or computes) it.
* "deterministically" IMO can never be used with "generate", as "generate" implies "non deterministically", otherwise it's not generation, it's computation.
* "site-specific": I don't understand this term, or how it helps make the documentation clearer.
* "user-defined password": I think that "user-provided" is better.
* "a key": was changed multiple times to "the key". We are talking about _the_ key that will be used for encryption by CredHub, not any AES key.
* "lifetime of the server": this precison feels superfluous, and confusing. The lifetime of the CredHub server is so far about 7 years. I understand that the author meant "until the server instance stops running". I thought …

Fix: confusing phrasing

---

build.gradle

- As it is latest version 5 patch and CVE-free.
[#187137257]

bump: Spring Framework to 5.3.32

---

applications/credhub-api/src/main/resources/db/migration/mysql/V57_2__delete_related_encrypted_value_when_credential_is_deleted.sql
applications/credhub-api/src/main/resources/db/migration/postgres/V57_2__delete_related_encrypted_value_when_credential_is_deleted.sql
components/credentials/src/test/java/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataServiceTest.java

- When a credential was deleted, its related encrypted_value records were not being deleted.
- Implemented a trigger to make sure that those records are deleted.
[#182121168]
There will be more commits, including tests, triggers for other databases and indexes to address delete operation performance.

fix: Orphaned encrypted_value records

---

applications/credhub-api/src/main/resources/db/migration/h2/V57_2__delete_related_encrypted_value_when_credential_is_deleted.sql
applications/credhub-api/src/main/resources/db/migration/mysql/V57_2__delete_related_encrypted_value_when_credential_is_deleted.sql
applications/credhub-api/src/main/resources/db/migration/postgres/V57_2__delete_related_encrypted_value_when_credential_is_deleted.sql
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateVersionDeleteTest.java
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/entity/CredentialVersionData.kt
components/credentials/src/test/java/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataServiceTest.java
components/encryption/src/main/java/org/cloudfoundry/credhub/data/CredentialVersionDeleteTrigger.java
components/encryption/src/main/java/org/cloudfoundry/credhub/data/PasswordOrUserCredentialDeleteTrigger.java

Fix for issue https://github.com/cloudfoundry/credhub/issues/231
Changes include:
- Database triggers to delete encrypted_value records when `credential` or `credential_version` is deleted
- Removal of cacscade delete in JPA entity for credential_version as it interferes with the database triggers

182121168 del encrypted values 2

---

build.gradle

- spring-boot 2.7.18 provides spring-security 2.7.11, which has CVE-2024-22257. So, override that with spring-security 2.7 latest patch version. This should be removed once spring-boot version is bumped.
[#187358318]

Bump: spring-security to 5.7.12

---

backends/credhub/build.gradle
backends/remote/build.gradle
build.gradle
components/credentials/build.gradle
components/encryption/build.gradle

Documenting instead of adding to dependabot ignore list. Will have to disregard 4.x `protobuf` dependabot PRs for a while, but the expectation is that `grpc` will be updated  to bump its dependency to `protobuf` in near future, hopefully.

doc: The need to stay with protobuf 3.25.x

---

applications/credhub-api/src/main/resources/db/migration/postgres/V58__remove_triggers.sql

- Fixed the drop operation order for the following error:
```
ERROR: cannot drop function del_credential_version_encrypted_value() because other objects depend on it
Detail: trigger tr_credential_version_post_del on table credential_version depends on function del_credential_version_encrypted_value()
```

fix: postgres script error

---

build.gradle

- Overrode spring-boot-managed `io.netty` dependency with latest patch version.
[#187358314]

fix: CVE in `io.netty.netty-codec-http`

---

backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateVersionDeleteTest.java
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/entity/Credential.kt
components/credentials/src/test/java/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataServiceTest.java

Re-implemented fix for https://github.com/cloudfoundry/credhub/issues/231 with JPA cascade-remove instead of database triggers. See commit messages for further details.

187367323 dbs not allowing trigger creation

---

backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateVersionDeleteTest.java
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/entity/Credential.kt
components/credentials/src/test/java/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataServiceTest.java

Reverts cloudfoundry/credhub#726.
There is a postgresql-only test that failed:
```
org.cloudfoundry.credhub.handlers.DefaultCertificatesHandlerIntegrationTest > handleGetAllRequest_65536Certs_doesNotCrash
...
Object [id=8df2048d-8be8-45e5-9ec8-874d8481499d] was not of the specified subclass [org.cloudfoundry.credhub.entity.CredentialVersionData] : Discriminator: foo; nested exception is org.hibernate.WrongClassException: Object [id=8df2048d-8be8-45e5-9ec8-874d8481499d] was not of the specified subclass [org.cloudfoundry.credhub.entity.CredentialVersionData] : Discriminator: foo
org.springframework.orm.ObjectRetrievalFailureException: Object [id=8df2048d-8be8-45e5-9ec8-874d8481499d] was not of the specified subclass [org.cloudfoundry.credhub.entity.CredentialVersionData] : Discriminator: …
```

Revert "187367323 dbs not allowing trigger creation"

---

backends/credhub/src/test/java/org/cloudfoundry/credhub/handlers/DefaultCertificatesHandlerIntegrationTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CertificateVersionDeleteTest.java
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/entity/Credential.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/entity/CredentialVersionData.kt
components/credentials/src/test/java/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataServiceTest.java

- Fixed https://github.com/cloudfoundry/credhub/issues/231 in JPA layer instead of using database triggers.
- Used `LAZY` fetch for the JPA one-to-many mapping from `credential` to `crdential_version` because `EAGER` causes memory and perfromance issue when many credentials are loaded, e.g. `DefaultCertificatesHandler.handleGetAllRequest()`. The issue with `EAGER` fetch was reproducible in `DefaultCertificatesHandlerIntegrationTest`.
- Made `DefaultCertificatesHandlerIntegrationTest` transactional so as not to commit test data. This not only makes sure no dirty test data is left but also makes the test runs a little faster.
- Changed the `credetial_version.type` of test data in `DefaultCertificatesHandlerIntegrationTest` to a valid value 'cert' as previous invalid type value caused data …

fix: Orphaned encrypted_value when Credentials are deleted

---

README.md
backends/credhub/build.gradle
backends/credhub/src/docs/asciidoc/index.adoc
build.gradle
spring-rest-docs-config.gradle

- problem: script `/scripts/generate_documentation_snippets.sh`
fails with:
```
In plugin 'org.asciidoctor.convert' type 'org.asciidoctor.gradle.AsciidoctorTask' property 'logDocuments' is annotated with @optional but that is not allowed for 'Console' properties.
```
- It looks like our asciidoctor lib is out of date (EOL) and not compatible
with the new gradle. Hence, taking advice from
https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/600,
migrate to a supported lib instead (`org.asciidoctor.jvm.convert`);
and use the latest version of that.
- The changes in this commit follows this sample app: https://github.com/spring-projects/spring-restdocs-samples/blob/c98c705ad9043aa19db96ce29160e0fbdfeaf8bc/restful-notes-spring-hateoas/build.gradle
- note: The directory changes in …

fix: api docs build failure

---

.github/dependabot.yml

We need to stay with protobuf-java & protoc 3.25.x as the latest grpc 1.62.2 still depends on protobuf-java & protoc 3.25.x
this can be removed whenever new version of grpc that supports protobuf 4.x.x is released
https://github.com/grpc/grpc-java/issues/11015

dependabot to ignore protobuf bump

---

applications/credhub-api/src/main/resources/db/migration/mysql/V58__remove_triggers.sql

- issue: the "DROP TRIGGER" step of our MySQL DB migration fails when used with AWS RDS MySQL 5.7 due to:
```
(conn=127) You do not have the SUPER privilege and binary logging is enabled
```
- We decided that the best approach is to just remove this migration step, even though modifying past migrations is not recommended by flyway (but in the past, in our context removing migration steps have not created any problems).
- Note: This removal comes with a small problem where the triggers in question are not removed (because we do want these triggers to be removed, since they are not compatible with our latest code in terms of DB cleanup, see: https://github.com/cloudfoundry/credhub/pull/728). However, this problematic scenario should be quite narrow (only for users who have successfully …

fix: DB migration fails with AWS RDS MySQL 5.7

---

build.gradle

- Started overriding Tomcat version as older versions had CVEs.
- This fixes https://jira.eng.vmware.com/browse/TASCVE-12113.
- Bumped other overriding minor/patch versions to the later compatible ones.

bump: Dependency versions that we override Spring Boot's

---

backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CredentialFindTest.java
backends/credhub/src/test/java/org/cloudfoundry/credhub/integration/CredentialGetTest.java

- add test about get cred by name case-insensitively
- rename test about find cred by name-like to indicate it's about case-insensitivity (following the naming pattern of other similar existing tests)
- motivation: we are about to perform some DB query optimization in terms of how we do case-insensitive cred name search, so need to make sure we have clear test coverage on this area in:
- get cred by name (added in this commit)
- find cred by name-like (already covered, renamed in this commit to make clearer)
- delete by name (already covered)
[internal tracking: https://vmw-jira.broadcom.net/browse/TPCF-26571]

backfill tests: case-insensitive cred search

---

applications/credhub-api/src/main/resources/db/migration/h2/V59__add_lowercase_credential_name_column_and_index.sql
applications/credhub-api/src/main/resources/db/migration/mysql/V57__add_lowercase_credential_name_column.sql
applications/credhub-api/src/main/resources/db/migration/mysql/V58__index_lowercase_credential_name.sql
applications/credhub-api/src/main/resources/db/migration/postgres/V60__add_lowercase_credential_name_column.sql
applications/credhub-api/src/main/resources/db/migration/postgres/V61__index_lowercase_credential_name.sql
components/credentials/src/main/java/org/cloudfoundry/credhub/services/CredentialDataService.java
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/entity/Credential.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/repositories/CredentialRepository.kt
components/credentials/src/main/kotlin/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataService.kt
components/credentials/src/test/kotlin/org/cloudfoundry/credhub/services/CredentialDataServiceTest.kt

- queries improved for MySQL and Postgres (including get-by-cred-name, find-by-name-like, delete-by-name) by performing case-insensitive search more efficiently
details:
- product requirements
- The credential name itself is **case-sensitive** data (you store `/FooBar`, you get `/FooBar` back). But the cred search (credhub api's get-by-cred-name, get-by-cred-name-like, find-by-name endpoints) needs to be **case-insensitive** (you search `/fooBAR`, you still get `/FooBar` back).
- CredHub has to work with MySQL, Postgres, and H2 (though H2 is only for testing).
- problem statements (current state)
- For MySQL, the queries currently uppercase or lowercase the search: `upper(credential.name) = upper(searched_term)` (sometimes it's uppercase, sometimes lowercase; it's not consistent), and …

feat: improve DB query performance

---

applications/credhub-api/src/main/resources/db/migration/mysql/V58__index_lowercase_credential_name.sql

- mysql migration v58 failed flyway validation because there was a prior migration also numbered v58
(082fd5e91c68b9fb340184f8fb4548e661890b48) which had since been removed but nevertheless was recorded in flyway history for those users who have installed credhub versions containing the old v58, hence creating a conflict with the new v58. Hence, this commit removes the new v58 for now to fix the issue for those users.
- leaving v57 alone because there was never a v57 before, only v57_2, which flyway treats as distinct from v57. See code history here: https://github.com/cloudfoundry/credhub/commits/main/applications/credhub-api/src/main/resources/db/migration/mysql
- we will try to add back the index (in this removed v58) later in a safe way.
- also: leaving postgres & H2 migrations intact …

fix: issue #813 by removing problematic mysql migration

---

applications/credhub-api/src/main/resources/db/migration/mysql/V59__add_lowercase_credential_name_index.sql

- context: the performance improvement brought by indexing (#803) was reverted (#815) due to migration error (issue #813) for some users. This commit brings back that index, but doing so safely to avoid issues like #813 (#813 happened to some users due to migration file numbering conflict, this commit uses a fresh migration number (v59) to avoid that).
- Unfortunately, for the users who happened to have installed credhub v2.12.94 successfully (aka did not encounter #813), their mysql DB would already have an index called
"credential_name_lowercase". So in order for the migration in this commit to work for both those who have installed credhub v2.12.94 and those who have not, this commit's migration instead creates the index under a different name: "credential_name_lowercase_index" (mysql …

feat: add back index on credential lowercase name

---

gradle/wrapper/gradle-wrapper.properties
gradlew

- Done by following the steps at https://docs.gradle.org/8.12/userguide/upgrading_version_8.html.

bump: gradle to 8.12

---

components/test-support/src/test/kotlin/org/cloudfoundry/credhub/utils/AuthConstants.kt

- Had a space at the beginning of the vaiue.
- Was not an issue with old oauth2 lib.
- But `spring-security-oauth2-resource-server` considers it as malformed.

fix: a test JWT data

---

components/auth/src/main/java/org/cloudfoundry/credhub/config/AuthConfiguration.java
components/auth/src/test/kotlin/org/cloudfoundry/credhub/auth/OAuth2ExtraValidationFilterTest.kt

fix: a test data overriding
- Spying `oAuth2IssuerService!!.getIssuer()` does not work with modified `AuthConfiguration` as `jwtDecoder` bean is created at the startup.
- Instead, to manipulate the issuerURI, just replace `jwtDecoder`'s `JwtValidator` to a desired one.
- Also changed `AuthConfiguration.jwtDecoder()` to return `NimbusJwtDecoder` so we don't have to downcast it in the test code.

New oauth2 when given valid issuer returns200

---

components/auth/src/main/java/org/cloudfoundry/credhub/config/AuthConfiguration.java
components/auth/src/main/java/org/cloudfoundry/credhub/config/auth/OAuth2AuthenticationExceptionHandler.java
components/auth/src/test/kotlin/org/cloudfoundry/credhub/auth/OAuth2ExtraValidationFilterTest.kt

- As we did in the existing credhub implemenmtation.
- However, instead of providing customized `error_description` string as we did in the existing credhub implementation, provide the `error_description` from `spring-security`, i.e. the same ones that are provided in the response header.
- It is because, unlikely the existing credhub implementation, we cannot tell exact kind of error based on the cause exceptions. For example, invalid issuer and expired token have the same cause exception but with specific error messages.
Making it as Draft PR for now, as I want to perform additional tasks as follows:
- Test with credhub-cli.
- Take another look at the option to provide customized `error_description` string as we did in the existing credhub implementation. I did spent quite some time on …

feat: Provide OAuth error info in response body.

---

build.gradle

- This also fixes https://github.com/cloudfoundry/credhub/issues/872, which was caused by a changed made in Tomcat 9.0.100.

bump: Tomcat 9 to latest patch 9.0.102

---

components/auth/src/main/java/org/cloudfoundry/credhub/auth/CredHubJwtTimeValidator.java
components/auth/src/main/java/org/cloudfoundry/credhub/auth/OAuth2AuthenticationExceptionHandler.java
components/auth/src/main/java/org/cloudfoundry/credhub/config/AuthConfiguration.java
components/auth/src/test/java/org/cloudfoundry/credhub/auth/OAuth2AuthenticationExceptionHandlerTest.java
components/auth/src/test/kotlin/org/cloudfoundry/credhub/auth/OAuth2ExtraValidationFilterTest.kt

fix: response error for expired access token
- Recent change of the error code was not compatible with `credhub-cli`, which is expecting a specific error code for expired access token.
- That apparently affected concourse use case.
- Modified the error code and description of the response for expired access token to match credhub 2.12.x implementation.

Custom jwt timestamp validator

---

backends/shared-backend-configuration/src/main/kotlin/org/cloudfoundry/credhub/config/WebMvcConfiguration.kt

- after bumping to spring boot 3
- error:
```
credhub curl -p /api/v1/certificates/
An application error occurred. Please contact your CredHub administrator.
```
when `credhub curl -p /api/v1/certificates` works
- To maintain backward compatibility, especially given that our acceptance test as well as some cli code (e.g.: https://github.com/cloudfoundry/credhub-cli/blob/11f3a43db498ee7f2adb8e19afcf3b1781d6e6ff/credhub/certificates.go#L32) still includes the trailing slash, we should maintain the old behavior when there is a trailing slash
- reference: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes
- this `setUseTrailingSlashMatch` method in the guide is marked as deprecated, but so is many other methods used …

fix: failure to get certs when request path has a trailing slash

---

.github/dependabot.yml
applications/credhub-api/build.gradle
backends/credhub/build.gradle
backends/shared-backend-configuration/build.gradle
build.gradle
components/auth/build.gradle
components/credentials/build.gradle
components/encryption/build.gradle
components/permissions/build.gradle

- See individual commits
- out of scope: the deps brought in by spring boot by default that are major version(s) behind what we explicitly pinned / bring in (don't wanna downgrade anything by a major version, e.g. flyway, even though it's probably not a big deal, since spring boot often values stability).

Various dependency refactors and organization

---

applications/credhub-api/src/main/resources/db/migration/h2/V25_2__relate_named_secrets_to_named_secret_table.sql

This reverts commit fd7d79ba753ad9030400d89fd12ce53b9c87d1f1.
- as we were hoping (see: https://github.com/cloudfoundry/credhub/commit/fd7d79ba753ad9030400d89fd12ce53b9c87d1f1) the original problem went away after the codebase's deps are systematically bumped as a whole.
- so we don't need this "temp fix" (which is not good because it creates a kink, a divergence between h2 and mysql/postgres that we don't want)
[https://vmw-jira.broadcom.net/browse/TNZ-38508]

Revert "temp fix: strange h2 column type mismatch error"

---

backends/shared-backend-configuration/src/main/kotlin/org/cloudfoundry/credhub/config/WebMvcConfiguration.kt

- Both properties are set to `false` by default, so no need to set it explicitly.

remove: Use of deprecated WebMvcConfigurer API methods

---

backends/shared-backend-configuration/src/main/kotlin/org/cloudfoundry/credhub/config/WebMvcConfiguration.kt
components/auth/src/main/java/org/cloudfoundry/credhub/config/AuthConfiguration.java

- Changed to use `UrlHandlerFilter` instead.
- To keep accepting URLs with trailing slashes.

remove: Use of deprecated `WebMvcConfigurer.setUseTrailingSlashMatch()`

---

components/credentials/src/main/java/org/cloudfoundry/credhub/generators/SshGenerator.java
components/credentials/src/main/java/org/cloudfoundry/credhub/utils/CertificateReader.java
components/credentials/src/main/java/org/cloudfoundry/credhub/utils/JsonObjectMapper.java
components/credentials/src/test/java/org/cloudfoundry/credhub/generators/SignedCertificateGeneratorTest.java
components/credentials/src/test/java/org/cloudfoundry/credhub/requests/CertificateGenerationRequestParametersTest.java
components/credentials/src/test/java/org/cloudfoundry/credhub/services/DefaultCredentialVersionDataServiceTest.java

- In `:components:credentials`.
- The remaining ones noted in TNZ-44144.

replace: Deprecated API calls

---

ktlint.gradle

- Replaced one.
- All the remaining deprecation warnings are for the features that are to be removed in Gradle 10.
For TNZ-44286.

replace: Feature that is to be removed in Gradle 9.
